services:
  web:
    container_name: web
    build: docker/dev
    tty: true
    ports:
      - '3333:3333'
      - '7001:7001'
    env_file:
      - .env
    volumes:
      - .:/server
    networks:
      - app-network

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql

networks:
  app-network:
    driver: bridge
