services:
  # web:
  #   container_name: web
  #   build: docker/dev
  #   tty: true
  #   ports:
  #     - '3333:3333'
  #     - '7001:7001'
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/server
  #   networks:
  #     - app-network

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - ./.docker/mongodb/db:/data/db

  redis:
    container_name: redis
    image: wodby/redis
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
